### ISSUE TITLE
港澳台 电视好像不能用了

### ISSUE THREAD

**Issue by lalasou** [amygoTV/MyTV#1]
港澳台 电视好像不能用了

还是用github 吧   gitee   会删库 会屏蔽
github 可以用公益加速

**Comment by amygoTV** [comment]
那你可以用啊，我弄的有呀，不都说github加载慢吗？https://gitee.com/amygotv/tv/raw/master/zheteng.json这个多仓，摸鱼儿里面的直播是这个源，第三个仓库是github的



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年1月15日(周一) 中午11:45
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [amygoTV/MyTV] 港澳台 电视好像不能用了 (Issue #1)




 
港澳台 电视好像不能用了
 
还是用github 吧   gitee   会删库 会屏蔽
 github 可以用公益加速

**Comment by lalasou** [comment]
> 那你可以用啊，我弄的有呀，不都说github加载慢吗？https://gitee.com/amygotv/tv/raw/master/zheteng.json这个多仓，摸鱼儿里面的直播是这个源，第三个仓库是github的
> 
> 
> 
> 
> 
> 
> 
> ---原始邮件---
> 
> 发件人: ***@***.***&gt;
> 
> 发送时间: 2024年1月15日(周一) 中午11:45
> 
> 收件人: ***@***.***&gt;;
> 
> 抄送: ***@***.***&gt;;
> 
> 主题: [amygoTV/MyTV] 港澳台 电视好像不能用了 (Issue #1)
> 
> 
> 
> 
> 
> 
> 
> 
> 
>  
> 
> 港澳台 电视好像不能用了
> 
>  
> 
> 还是用github 吧   gitee   会删库 会屏蔽
> 
>  github 可以用公益加速
> 
>  
> 
> —
> 
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 
> You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

大佬   港澳台更新下  

他这个可以用  
https://github.com/Meroser/IPTV/blob/main/IPTV.m3u

**Comment by amygoTV** [comment]
好的，晚上吧



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年1月15日(周一) 中午12:26
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [amygoTV/MyTV] 港澳台 电视好像不能用了 (Issue #1)




  
那你可以用啊，我弄的有呀，不都说github加载慢吗？https://gitee.com/amygotv/tv/raw/master/zheteng.json这个多仓，摸鱼儿里面的直播是这个源，第三个仓库是github的
 
---原始邮件---
 
发件人: @.***&gt;
 
发送时间: 2024年1月15日(周一) 中午11:45
 
收件人: @.***&gt;;
 
抄送: @.***&gt;;
 
主题: [amygoTV/MyTV] 港澳台 电视好像不能用了 (Issue #1)
 
港澳台 电视好像不能用了
 
还是用github 吧   gitee   会删库 会屏蔽
 
github 可以用公益加速
 
—
 
Reply to this email directly, view it on GitHub, or unsubscribe.
 
You are receiving this because you are subscribed to this thread.Message ID: @.***&gt;
  
大佬   港澳台更新下
 
他这个可以用
 https://github.com/Meroser/IPTV/blob/main/IPTV.m3u

**Comment by amygoTV** [comment]
已更新



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年1月15日(周一) 中午12:26
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [amygoTV/MyTV] 港澳台 电视好像不能用了 (Issue #1)




  
那你可以用啊，我弄的有呀，不都说github加载慢吗？https://gitee.com/amygotv/tv/raw/master/zheteng.json这个多仓，摸鱼儿里面的直播是这个源，第三个仓库是github的
 
---原始邮件---
 
发件人: @.***&gt;
 
发送时间: 2024年1月15日(周一) 中午11:45
 
收件人: @.***&gt;;
 
抄送: @.***&gt;;
 
主题: [amygoTV/MyTV] 港澳台 电视好像不能用了 (Issue #1)
 
港澳台 电视好像不能用了
 
还是用github 吧   gitee   会删库 会屏蔽
 
github 可以用公益加速
 
—
 
Reply to this email directly, view it on GitHub, or unsubscribe.
 
You are receiving this because you are subscribed to this thread.Message ID: @.***&gt;
  
大佬   港澳台更新下
 
他这个可以用
 https://github.com/Meroser/IPTV/blob/main/IPTV.m3u

**Comment by amygoTV** [comment]
不能用就自己找源，自己做链接



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年1月16日(周二) 下午2:19
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [amygoTV/MyTV] 港澳台 电视好像不能用了 (Issue #1)




 
Closed #1 as completed.
